import { TopDBLayout } from "@/components/Dashboard/DBLayout/TopDBLayout";
import "../globals.css";
import "./dashboard.css";
import { LeftDBLayout } from "@/components/Dashboard/DBLayout/LeftDBLayout";
export const metadata = {
  title: "unitech dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dashboard-max-w-screen-xl mx-auto`}>
        <div className="flex">
          <div className="dashboard-left-container md:block hidden border-r-2 border-l-2">
            <LeftDBLayout />
          </div>
          <div className="dashboard-body border-t-2 border-b-2">
            <TopDBLayout />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
